bunnybar/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from bunnybar.initialize import initialize
# from rest_framework_swagger.views import get_swagger_view

# schema_view = get_swagger_view(title='API')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', include('cocktails.urls')),
    path('', include('products.urls')),
    path('initialize/', initialize),
    # url(r'swagger/', schema_view),
]

cocktails/urls.py
from . import views
from django.urls import path, include
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'attached-materials', views.AttachedMaterialViewSet)
router.register(r'alcohols', views.AlcoholViewSet)
router.register(r'cocktails', views.CocktailViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('index/cocktails', views.cocktail_index, name='index_cocktails'),
]

products/urls.py
from . import views
from django.urls import path

urlpatterns = [
]

cocktails/models.py
from django.db import models

# Create your models here.
ALCOHOL_TYPES = [
    ('Rum', 'Rum'),
    ('Brandy', 'Brandy'),
    ('Tequila', 'Tequila'),
    ('Whisky', 'Whisky'),
    ('Vodka', 'Vodka'),
    ('Gin', 'Gin'),
    ('Liqueur', 'Liqueur'),
    ('Beer', 'Beer'),
    ('Wine', 'Wine'),
    ('Champagne', 'Champagne'),
    ('Vermouth', 'Vermouth'),
    ('Absinthe', 'Absinthe'),
    ('Bitters', 'Bitters'),
    ('Sake', 'Sake'),
    ('Soju', 'Soju'),
    ('Others', 'Others'),
]


class Alcohol(models.Model):
    name = models.CharField(max_length=100, unique=True)
    alcohol_type = models.CharField(max_length=10, choices=ALCOHOL_TYPES)


class AttachedMaterial(models.Model):
    name = models.CharField(max_length=100, unique=True)


class Cocktail(models.Model):
    name = models.CharField(max_length=100, unique=True)
    recipe = models.TextField(max_length=200)
    alcohols = models.ManyToManyField(Alcohol)
    attached_materials = models.ManyToManyField(
        AttachedMaterial, blank=True)
    image = models.ImageField(upload_to='static/images/', null=True)

products/models.py
from cocktails.models import Alcohol, AttachedMaterial
from django.core.validators import MinValueValidator
from django.db import models

# Create your models here.


class AlcoholicProduct(models.Model):
    name = models.CharField(max_length=100)
    alcohol = models.ForeignKey(Alcohol, on_delete=models.CASCADE)
    price = models.IntegerField(default=0, validators=[MinValueValidator(0)])


class OtherProduct(models.Model):
    name = models.CharField(max_length=100)
    attached_material = models.ForeignKey(
        AttachedMaterial, on_delete=models.CASCADE)
    price = models.IntegerField(default=0, validators=[MinValueValidator(0)])

cocktails/forms.py
from cocktails.models import Cocktail
from cocktails.models import Alcohol, AttachedMaterial, ALCOHOL_TYPES
from django import forms
from django.core.exceptions import ValidationError


class NameModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.name


class NameModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.name


class CocktailCreateForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100, required=True)
    alcohol_type = forms.ChoiceField(
        required=True, choices=[(None, 'Select')] + ALCOHOL_TYPES)
    alcohol = NameModelChoiceField(
        required=True, empty_label='Select', queryset=Alcohol.objects.order_by('name'))
    attached_materials = NameModelMultipleChoiceField(
        required=False, queryset=AttachedMaterial.objects.order_by('name'))
    recipe = forms.CharField(
        max_length=200, widget=forms.Textarea(attrs={'rows': 8, }))
    image = forms.ImageField(required=True)

    def clean_name(self):
        name = self.cleaned_data['name']
        if Cocktail.objects.filter(name=name).exists():
            raise forms.ValidationError(
                'Cocktail "' + name + '" already exists')
        return name

    def clean_alcohol(self):
        alcohols_id = self.data.getlist('alcohol')
        alcohols = Alcohol.objects.filter(id__in=alcohols_id)
        return alcohols

    def save(self):
        cocktail = Cocktail(
            name=self.cleaned_data['name'], recipe=self.cleaned_data['recipe'], image=self.cleaned_data['image'])
        cocktail.save()
        for alcohol in self.cleaned_data['alcohol']:
            cocktail.alcohols.add(alcohol)
        for attached_material in self.cleaned_data['attached_materials']:
            cocktail.attached_materials.add(attached_material)

cocktails/views.py
from cocktails.forms import CocktailCreateForm
from cocktails.models import Alcohol, AttachedMaterial, Cocktail
from cocktails.serializers import AlcoholSerializer, AttachedMaterialSerializer, CocktailSerializer
from django.http import HttpResponse
from django.shortcuts import redirect, render
from rest_framework import viewsets, permissions, filters

# Create your views here.


def cocktail_index(request):
    cocktails = Cocktail.objects.order_by('name').all()

    if request.method == 'POST':
        create_form = CocktailCreateForm(request.POST, request.FILES)
        if create_form.is_valid():
            create_form.save()
            return redirect('index_cocktails')
    else:
        create_form = CocktailCreateForm()

    context = {
        'cocktails': cocktails,
        'create_form': create_form,
    }
    return render(request, 'cocktail.html', context=context)

# restful api using django restful framework


class AlcoholViewSet(viewsets.ModelViewSet):
    queryset = Alcohol.objects.all()
    serializer_class = AlcoholSerializer
    # permission_classes = [permissions.IsAuthenticated]
    filter_backends = [filters.SearchFilter]
    search_fields = ['name', '=alcohol_type']


class AttachedMaterialViewSet(viewsets.ModelViewSet):
    queryset = AttachedMaterial.objects.all()
    serializer_class = AttachedMaterialSerializer
    # permission_classes = [permissions.IsAuthenticated]
    filter_backends = [filters.SearchFilter]
    search_fields = ['name']


class CocktailViewSet(viewsets.ModelViewSet):
    queryset = Cocktail.objects.all()
    serializer_class = CocktailSerializer

    def get_queryset(self):
        queryset = Cocktail.objects.all()

        name = self.request.query_params.get('name', None)
        alcohol = self.request.query_params.get('alcohol', None)
        alcohol_type = self.request.query_params.get('alcohol_type', None)

        if name:
            queryset = queryset.filter(name__contains=name)
        if alcohol:
            queryset = queryset.filter(alcohols__name=alcohol)
        if alcohol_type:
            queryset = queryset.filter(alcohols__alcohol_type=alcohol_type)

        return queryset

    # permission_classes = [permissions.IsAuthenticated]

products/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Title{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        {% block styles %}{% endblock styles %}
        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="{% static 'fontawesome-free-5.15.2-web/css/all.css' %}">
    </head>
    <body>
        <nav class="navbar">
            <span class="navbar-brand h1">BunnyBar</span>
        </nav>
        {% block content %}
        {% endblock content %}

        <!-- JQuery -->
        <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
        <!-- Bootstrap -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        {% block scripts %}
        {% endblock scripts %}
    </body>
</html>

templates/cocktail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cocktails{% endblock title %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/cocktail.css' %}">
{% endblock styles %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-8 offset-2">
            <h2>Cocktails</h2>
            <!-- 新增cocktail按鈕 -->
            <button id="btn-modal-create" class="btn btn-outline-secondary fas fa-plus-square" type="button" data-toggle="modal" data-target="#modal-create"></button>
            <!-- 搜尋列 -->
            <div id="filter-input-group" class="input-group">
                <div class="input-group-prepend">
                    <button id="filter-param" class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cocktail Name</button>
                    <div id="filter-param-list" class="dropdown-menu">
                        <li id="filter-param-alcohol-type" class="dropdown-item">Base</li>
                        <li id="filter-param-name" class="dropdown-item">Cocktail Name</li>
                        <li id="filter-param-alcohol" class="dropdown-item">Alcohol Name</li>
                    </div>
                </div>
                <input id="filter-data" type="text" class="form-control" placeholder="Cocktail Name">
                <div class="input-group-append">
                    <button id="filter-submit" class="btn btn-outline-secondary fas fa-search" type="button" value="name"></button>
                </div>
            </div>
            <!-- cocktail列表 -->
            <div id="cocktails-field" class="row">
                {% for cocktail in cocktails %}
                <div class="col-3">
                    <div id="{{cocktail.id}}" class="card">
                        {% if cocktail.image %}
                        <img class="card-image-top" src="{{ cocktail.image.url }}">
                        {% endif %}
                        <div class="card-body">
                            <h4 class="card-title">{{ cocktail.name }}</h4>
                            <p>{% for alcohol in cocktail.alcohols.all %}{{ alcohol.name }} {% endfor %}
                                {% for attached_material in cocktail.attached_materials.all %}{{ attached_material.name }} {% endfor %}</p>
                            <button class="btn btn-primary btn-modal-detail" type="button" data-toggle="modal" data-target="#modal-detail" value="{% url 'cocktail-detail' cocktail.id %}">Recipe</ㄖ>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<!-- 新增cocktail表單modal -->
<div id="modal-create" class="modal fade" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Create Cocktail</h4>
                <button class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'index_cocktails' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label class="col-2 col-form-label">{{ create_form.name.label }}</label>
                        <div class="col-10">
                            {{ create_form.name.errors }}
                            {{ create_form.name }}
                        </div>
                    </div>
                    <div id="create-form-alcohols-field">
                        <div class="row form-group">
                            <label class="col-2 col-form-lable">{{ create_form.alcohol.label }}</label>
                            <div class="col-4">
                                {{ create_form.alcohol_type.errors }}
                                {{ create_form.alcohol_type }}
                            </div>
                            <div class="col-4">
                                {{ create_form.alcohol.errors }}
                                {{ create_form.alcohol }}
                            </div>
                            <div class="col-2">
                                <button class="btn fas fa-plus-square btn-add-alcohol" type="button"></button>
                                <button class="btn fas fa-minus-square btn-remove-alcohol" type="button"></button>
                            </div>
                        </div>
                    </div>
                    <div class="row form-group">
                        <label class="col-2 col-form-label">{{ create_form.attached_materials.label }}</label>
                        <div class="col-10">
                            {{ create_form.attached_materials.errors }}
                            {{ create_form.attached_materials }}
                        </div>
                    </div>
                    <div class="row form-group">
                        <label class="col-2 col-form-label">{{ create_form.recipe.label }}</label>
                        <div class="col-10">
                            {{ create_form.recipe.errors }}
                            {{ create_form.recipe }}
                        </div>
                    </div>
                    <div class="row form-group">
                        <label class="col-2 col-form-label">{{ create_form.image.label }}</label>
                        <div class="col-10">
                            {{ create_form.image.errors }}
                            {{ create_form.image }}
                        </div>
                    </div>
                    <button id="create-submit" class="btn btn-primary" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- cocktail資料modal -->
<div id="modal-detail" class="modal fade" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Cocktail Detail</h4>
            </div>
            <div class="modal-body">
                <table class="table table-striped table-borderless">
                    <tbody>
                        <tr>
                            <td>名稱</td>
                            <td id="detail-name"></td>
                        </tr>
                        <tr>
                            <td>主材料</td>
                            <td id="detail-alcohols"></td>
                        </tr>
                        <tr>
                            <td>副材料</td>
                            <td id="detail-attached-materials"></td>
                        </tr>
                        <tr>
                            <td>製作方法</td>
                            <td id="detail-recipe"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    $(document).ready(function(){
        // 調整圖片高度
        $("img").each(function(){
            $(this).height($(this).width() * 0.75);
        });

        // 搜尋選單變更
        $("#filter-param-alcohol-type").click(function(){
            $("#filter-param").text($(this).text());
            $("#filter-data").val("").prop("placeholder", "Brandy/Gin/Rum/Tequila/Vodka/Whisky");
            $("#filter-submit").prop("value", "alcohol_type");
        });
        $("#filter-param-alcohol").click(function(){
            $("#filter-param").text($(this).text());
            $("#filter-data").val("").prop("placeholder", "Alcohol Name");
            $("#filter-submit").prop("value", "alcohol");
        });
        $("#filter-param-name").click(function(){
            $("#filter-param").text($(this).text());
            $("#filter-data").val("").prop("placeholder", "Cocktail Name");
            $("#filter-submit").prop("value", "name");
        });

        // 搜尋調酒
        $("#filter-submit").click(function(){
            let param = $(this).val();
            let ajax_data = {};
            if (param == "name") {
                ajax_data["name"] = $("#filter-data").val();
            } else if (param == "alcohol") {
                ajax_data["alcohol"] = $("#filter-data").val();
            } else {
                ajax_data["alcohol_type"] = $("#filter-data").val();
            }
            $.ajax({
                url: "{% url 'cocktail-list' %}",
                type: "GET",
                data: ajax_data,
                dataType: "json",
                success: function(data){
                    $("#cocktails-field").children(".col-3").hide();
                    $.each(data, function(ind, val){
                        $("#" + val["id"]).parent("div").show();
                    });
                },
            });
        });

        // 新增調酒表單 - 儲存已選擇的酒類
        let selected_alcohols = [];
        let update_selected_alcohols = function(){
            selected_alcohols = [];
            $("#create-form-alcohols-field").children(".row").each(function(index, elem){
                selected_alcohols.push($(elem).find("#id_alcohol").val());
            });
            console.log(selected_alcohols);
        };
        // 新增調酒表單 - 酒類選單選項調整
        $("#id_alcohol").children("option").hide();
        $("#id_alcohol").children("option").first().show();
        $("#create-form-alcohols-field").on("change", "#id_alcohol", function(){
            update_selected_alcohols();
        });
        $("#create-form-alcohols-field").on("change", "#id_alcohol_type", function(){
            let alcohol_row = $(this).parents(".row");
            if ($(this).val() == "") {
                $(alcohol_row).find("#id_alcohol").children("option").hide();
                $(alcohol_row).find("#id_alcohol").children("option").first().show().prop("selected", true);
            } else {
                $.ajax({
                    url: "{% url 'alcohol-list' %}",
                    type: "GET",
                    data: {search: $(this).val()},
                    dataType: "json",
                    success: function(data){
                        $(alcohol_row).find("#id_alcohol").children("option").hide();
                        $(alcohol_row).find("#id_alcohol").children("option").first().show().prop("selected", true);
                        $.each(data, function(ind, val){
                            $(alcohol_row).find("#id_alcohol option[value=" + val["id"] + "]").show();
                        });
                        $.each(selected_alcohols, function(ind, val){
                            $(alcohol_row).find("#id_alcohol option[value=" + val + "]").hide();
                        });
                    },
                });
            }
        });

        // 新增調酒表單 - 酒類增減按鈕
        $(".btn-remove-alcohol").hide();
        $(".btn-add-alcohol").click(function(){
            let new_alcohol = $(this).parents(".row").clone();
            $(new_alcohol).find(".btn-add-alcohol").hide();
            $(new_alcohol).find(".btn-remove-alcohol").show();
            $(new_alcohol).find("#id_alcohol_type").val("");
            $(new_alcohol).find("#id_alcohol").children("option").hide();
            $(new_alcohol).find("#id_alcohol").children("option").first().show();
            $("#create-form-alcohols-field").append($(new_alcohol));
        });
        $("#create-form-alcohols-field").on("click", ".btn-remove-alcohol", function(){
            $(this).parents(".form-group").remove();
            update_selected_alcohols();
        });

        // 如果create form有Error的話顯示彈出視窗
        if ($("#modal-create").find(".errorlist").length != 0) {
            console.log($("#modal-create").find(".errorlist"));
            $("#modal-create").modal();
        }

        // 顯示detail彈出視窗資料
        $(".btn-modal-detail").click(function(){
            let cocktail_url = $(this).val();
            $.ajax({
                url: cocktail_url,
                type: "GET",
                dataType: "json",
                success: function(data){
                    $("#detail-name").text(data["name"]);
                    $("#detail-recipe").html(data["recipe"].replaceAll("\r\n", "<br>"));
                    let alcohols_name = "";
                    $.each(data["alcohols"], function(i, alcohol){
                        alcohols_name += alcohol["name"] + " ";
                    });
                    $("#detail-alcohols").text(alcohols_name);
                    let attached_materials_name = "";
                    $.each(data["attached_materials"], function(i, attached_material){
                        attached_materials_name += attached_material["name"] + " ";
                    });
                    $("#detail-attached-materials").text(attached_materials_name);
                },
            });
        });
    });
</script>
{% endblock scripts %}